name:                pjlang
version:             0.1.0.0
github:              "pjanczyk/pjlang"
license:             GPL-3
author:              "Piotr Janczyk"
copyright:           "2018 Piotr Janczyk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Interpreter of PJ programming language
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/pjlang#readme>

dependencies:
- base >= 4.7 && < 5
- parsec == 3.1.11
- containers == 0.5.10.2
- transformers == 0.5.2.0
- either == 4.5
- text == 1.2.2.2
- HUnit == 1.6.0.0

library:
  source-dirs: src

executables:
  pjlang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pjlang

tests:
  pjlang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pjlang
